### ISSUE TITLE
Cyan::UID_t未重载"<"导致编译失败

### ISSUE THREAD

**Issue by rikukiix** [cyanray/mirai-cpp#100]
如题，linux gcc9.3.0下:
```
[build] /usr/include/c++/9/bits/stl_function.h:386:20: error: no match for ‘operator<’ (operand types are ‘const Cyan::GID_t’ and ‘const Cyan::GID_t’)
[build]   386 |       { return __x < __y; }
[build]       |                ~~~~^~~~~
```
MSVC16.7.5下出现类似问题。
在`mirai-cpp/include/mirai/defs/qq_types.hpp`中对`Cyan::UID_t`重载小于号后可以正常编译运行。

**Comment by cyanray** [comment]
感谢反馈
不过能不能提供出错的代码
是放到 map 之类的容器里会出错吗？

**Comment by rikukiix** [comment]
> 感谢反馈
> 不过能不能提供出错的代码
> 是放到 map 之类的容器里会出错吗？

是这样的，比如。。。提供的template里就有这样的问题（

**Comment by cyanray** [comment]
我在MSVC 16.9 和 GCC 10.2 上没有复现这个错误，可能是编译器的黑科技？
我只能简单修一下，看看有没有用。
