### ISSUE TITLE
关于版本的疑问

### ISSUE THREAD

**Issue by HelloGwkki** [cyanray/mirai-cpp#108]
最新的 mirai-cpp 好像是 v2

并且 v1 的代码好像无法在 v2 上使用

**Comment by cyanray** [comment]
v1.x的一些接口已经被移除了，主要是与mah通信的部分(MiraiBot的构造函数，Auth和EventLoop函数被移除，新增了Connect，Disconnect，Reconnect函数)，当然没法在v2.x用v1.x的接口了。

不是很懂什么叫"把版本处理一下"。

**Comment by HelloGwkki** [comment]
好...谢谢您的回复 :)
