### ISSUE TITLE
安装问题，cmake相关

### ISSUE THREAD

**Issue by YXHXianYu** [cyanray/mirai-cpp#109]
跟着教程安装，安装到0x04 - 1.快速尝试 - (1)使用vs - 第四步：
为什么我vs里的调试是灰色的，点击不了？
上网查了下，好像是没有创建项目的原因，但cmake好像不需要创建项目？
我用文件夹打开，更改了examples设置，也重新保存了CMakeLists.txt文件生成了cmake，但还是没用？
对cmake和vs不太熟悉，求助QwQ

**Comment by cyanray** [comment]
问题解决了吗，可以具体说一下是什么样的问题以及如何解决的吗？
你的问题也许可以让文档变得更清晰易懂。

**Comment by YXHXianYu** [comment]
我对vs和cmake不太熟悉。
我修改了下cmakelists.txt文件，再重新保存，生成cmake，然后才能进行“调试”。
然后右上角绿色箭头的启动项那边要选择cpp对应的exe，比如这里的RepeatMessage.exe，才可以进行第四步的”调试和启动设置...“

所以这里第六步的图片好像要提前？不然没法进行第四步。

这个问题解决后我又遇到了一个问题，是关于编译出的可执行文件如何和mirai-api-http沟通的问题？
看了下其他接口，好像是利用WebSocket之类的东西沟通？
那正确的使用方式，是否是：同时打开两个exe(一个mirai-api-http，另一个编译出的RepeatMessage.exe)，通过websocket的参数设置，使得两个程序进行沟通，然后在mirai-api-http中登入账号，就可以使用？
我这部分知识没学过，研究了好久没怎么弄懂。

多谢！

**Comment by cyanray** [comment]
mirai-console + mirai-api-http 是一部分，要先启动它，这样 mirai-api-http 会提供 http 和 websocket 服务。
然后启动基于 mirai-cpp 的程序（不要将它视为插件，将它视为一个服务器程序）。mirai-cpp 会使用 mah 提供的 http 和 websocket 服务。
你需要让 mirai-cpp 的程序知道 mah 提供的 http(websocket) 服务的IP地址和端口。
找找你的代码里有没有这样一句：
```c++
SessionOptions opts = SessionOptions::FromCommandLine(argc, argv);
```
这说明你需要通过命令行告诉 mirai-cpp 这些信息。

[文档](https://github.com/cyanray/mirai-cpp/blob/master/doc/Documentation.md#%E5%A6%82%E4%BD%95%E4%B8%8Emirai-api-http%E5%BB%BA%E7%AB%8B%E8%BF%9E%E6%8E%A5)已经提示了。

**Comment by YXHXianYu** [comment]
哦懂了懂了，感谢！
