### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by imag-er** [cyanray/mirai-cpp#110]
mah settings.yml:
    host: 0.0.0.0
    port: 12345
main.cpp:
    MiraiBot bot("0.0.0.0", 12345);
为啥实际使用时一直说网络错误
平台是树莓派raspbian

**Comment by cyanray** [comment]
0.0.0.0 改成 localhost 试试？
然后检测 mah 有没有正常工作：`curl http://localhost:12345/abot` 看看有没有响应

**Comment by imag-er** [comment]
> 0.0.0.0 改成 localhost 试试？
> 然后检测 mah 有没有正常工作：`curl http://localhost:12345/abot` 看看有没有响应

换成localhost没用,还是一样
mah貌似没有正常工作 
报错curl: (7) Failed to connect to localhost port 12345: Connection refused

**Comment by cyanray** [comment]
> > 0.0.0.0 改成 localhost 试试？
> > 然后检测 mah 有没有正常工作：`curl http://localhost:12345/abot` 看看有没有响应
> 
> 换成localhost没用,还是一样
> mah貌似没有正常工作
> 报错curl: (7) Failed to connect to localhost port 12345: Connection refused

那你应该先去解决 mah 的问题。你的 mah 也部署在树莓派吗？

**Comment by imag-er** [comment]
> > > 0.0.0.0 改成 localhost 试试？
> > > 然后检测 mah 有没有正常工作：`curl http://localhost:12345/abot` 看看有没有响应
> > 
> > 
> > 换成localhost没用,还是一样
> > mah貌似没有正常工作
> > 报错curl: (7) Failed to connect to localhost port 12345: Connection refused
> 
> 那你应该先去解决 mah 的问题。你的 mah 也部署在树莓派吗？

对
所有东西都在树莓派上

**Comment by cyanray** [comment]
> > > > 0.0.0.0 改成 localhost 试试？
> > > > 然后检测 mah 有没有正常工作：`curl http://localhost:12345/abot` 看看有没有响应
> > > 
> > > 
> > > 换成localhost没用,还是一样
> > > mah貌似没有正常工作
> > > 报错curl: (7) Failed to connect to localhost port 12345: Connection refused
> > 
> > 
> > 那你应该先去解决 mah 的问题。你的 mah 也部署在树莓派吗？
> 
> 对
> 所有东西都在树莓派上

可能是你没有正确地启动 mah，可以带着日志去 mah 的仓库发 issues。
