### ISSUE TITLE
提问：如何获取bot在群聊内的权限

### ISSUE THREAD

**Issue by sleepingzw** [cyanray/mirai-cpp#112]
权限是属于GroupMember下的一个变量
但是通过GetGroupMembers这个函数只能获取除bot外的群成员
请问怎样获取bot在特定群聊内的权限

也许有什么现成的函数可以直接获取？我反正没翻到（悲），可能是我眼瞎了罢

**Comment by cyanray** [comment]
使用 MiraiBot.GetGroupList 获取 Bot 的群列表，返回 std::vector<Group_t>。
Group_t.Permission 就是 bot 在该群的权限了。

可以在 mirai-api-http repo 提交 issues 让他们提供更直接的 api，我感觉这个需求还挺常见的？

**Comment by sleepingzw** [comment]
> 使用 MiraiBot.GetGroupList 获取 Bot 的群列表，返回 std::vector<Group_t>。
> Group_t.Permission 就是 bot 在该群的权限了。
> 
> 可以在 mirai-api-http repo 提交 issues 让他们提供更直接的 api，我感觉这个需求还挺常见的？

感谢您的解答，我去http-api那里发issue去了（）
