### ISSUE TITLE
websocket 连接正常，但是无法触发事件处理函数

### ISSUE THREAD

**Issue by Yastruhank** [cyanray/mirai-cpp#123]
你好。我在成功与mirai-apt-http建立连接之后尝试注册监听事件，但是事件发生后，注册的回调函数并没有被执行。在mirai主程序处能看到事件，并且不需要监听的发送消息功能也能正常使用，请问这是怎么回事呢？

**Comment by Yastruhank** [comment]
> 检查一下mah的配置文件，有没有开启ws(websocket)
> 
> 内容大概是：
> 
> ```
> adapter:
> - http
> - ws
> ```
> 
> 理论上没开启ws应该要抛出异常，但是不知道为何没有抛出异常。(难以抽出时间维护该项目，该问题可能长期存在)

mah的配置文件中是开启了ws的，并且在mirai主程序的控制台输出中也显示 Mirai HTTP API: adaptors: [http,ws]

**Comment by cyanray** [comment]
是所有事件都无法触发回调函数吗，具体是哪个事件呢？
有试过 FriendMessage, GroupMessage, Message 这类事件吗，有些不常用事件缺乏测试，可能哪里写错了没发现导致无法触发。

也试试捕捉事件解析错误：
```c++
bot.On<EventParsingError>([&](EventParsingError e)
{
    try
    {
        e.Rethrow();
    }
    catch (const std::exception& ex)
    {
        cout << "解析事件时出现错误: " << ex.what() << endl;
    }
});
```

更有可能是网络问题，检查 hostname，port 有没有设置错误。

**Comment by cyanray** [comment]
> > 是所有事件都无法触发回调函数吗，具体是哪个事件呢？ 有试过 FriendMessage, GroupMessage, Message 这类事件吗，有些不常用事件缺乏测试，可能哪里写错了没发现导致无法触发。
> > 也试试捕捉事件解析错误：
> > ```c++
> > bot.On<EventParsingError>([&](EventParsingError e)
> > {
> >     try
> >     {
> >         e.Rethrow();
> >     }
> >     catch (const std::exception& ex)
> >     {
> >         cout << "解析事件时出现错误: " << ex.what() << endl;
> >     }
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 更有可能是网络问题，检查 hostname，port 有没有设置错误。
> 
> 是所有事件都无法触发，包括例程也是。这个函数我也试了，也没有被触发。hostname和port应该没有配置出错。请问程序有日志系统之类的东西用来分析吗？

那就只能是网络问题了。

你可以试着在 [mirai_bot.cpp 的这一行](https://github.com/cyanray/mirai-cpp/blob/master/src/mirai_bot.cpp#L214) 打断点，看看新事件到达时会不会触发断点，如果不会，说明 Websocket 没成功建立连接。

然后在 [websocketClient.cpp 的这一行](https://github.com/cyanray/mirai-cpp/blob/master/include/mirai/third-party/WebSocketClient.cpp#L260)打断点，检查局部变量 response_buffer 的内容。（我猜测可能还没执行到这里就抛出异常了）

**Comment by cyanray** [comment]
> > > > 是所有事件都无法触发回调函数吗，具体是哪个事件呢？ 有试过 FriendMessage, GroupMessage, Message 这类事件吗，有些不常用事件缺乏测试，可能哪里写错了没发现导致无法触发。
> > > > 也试试捕捉事件解析错误：
> > > > ```c++
> > > > bot.On<EventParsingError>([&](EventParsingError e)
> > > > {
> > > >     try
> > > >     {
> > > >         e.Rethrow();
> > > >     }
> > > >     catch (const std::exception& ex)
> > > >     {
> > > >         cout << "解析事件时出现错误: " << ex.what() << endl;
> > > >     }
> > > > });
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 更有可能是网络问题，检查 hostname，port 有没有设置错误。
> > > 
> > > 
> > > 是所有事件都无法触发，包括例程也是。这个函数我也试了，也没有被触发。hostname和port应该没有配置出错。请问程序有日志系统之类的东西用来分析吗？
> > 
> > 
> > 那就只能是网络问题了。
> > 你可以试着在 [mirai_bot.cpp 的这一行](https://github.com/cyanray/mirai-cpp/blob/master/src/mirai_bot.cpp#L214) 打断点，看看新事件到达时会不会触发断点，如果不会，说明 Websocket 没成功建立连接。
> > 然后在 [websocketClient.cpp 的这一行](https://github.com/cyanray/mirai-cpp/blob/master/include/mirai/third-party/WebSocketClient.cpp#L260)打断点，检查局部变量 response_buffer 的内容。（我猜测可能还没执行到这里就抛出异常了）
> 
> 有进入第一个断点，在第二个断电response_buffe的内容是101 switching protocois
> 
> ![QQ截图20211017172303](https://user-images.githubusercontent.com/29678135/137620975-a8e9fd62-17a5-4b4a-b63c-ab5cedfe653f.png)

看起来没有问题啊，图中显示你收到了刚建立连接时MAH发的一个包，试着给你的机器人发条消息触发消息事件，看看还能进入第一个断点吗。

会不会是因为网络原因断开连接了，记得[处理 LostConnection 事件](https://github.com/cyanray/mirai-cpp/blob/master/doc/Documentation.md#%E5%A4%84%E7%90%86%E5%A4%B1%E5%8E%BB%E8%BF%9E%E6%8E%A5%E7%9A%84%E6%83%85%E5%86%B5)。

**Comment by cyanray** [comment]
这问题有点奇怪，我也看不懂了……

截图里你收到了 FriendInputStatusChangedEvent 事件，第一个断点你是否进入了两次？（第二次才是真正的好友消息事件）
试试 bot.On<FriendInputStatusChangedEvent> 看看能不能触发 FriendInputStatusChangedEvent 事件的回调函数。

**Comment by cyanray** [comment]
也可以加Q群 1013323391，可能交流方便点。// TODO: 将真实原因和解决方案回复在该帖子。

**Comment by cyanray** [comment]
错误原因：注释了 magic_enum 的断言，虽然通过编译，但是 magic_enum 不能正常工作。
解决方法：升级 MinGW

magic_enum 对编译器的要求：
- Clang/LLVM >= 5
- MSVC++ >= 14.11 / Visual Studio >= 2017
- Xcode >= 10
- GCC >= 9
- MinGW >= 9
