### ISSUE TITLE
关于MessageChain == 比较的问题 [Bug?]

### ISSUE THREAD

**Issue by Asada-Shino** [cyanray/mirai-cpp#131]
## 1
在[文档MessageChain部分](https://github.com/cyanray/mirai-cpp/blob/master/doc/Documentation.md#比较遍历和拼接-messagechain)中有
```
MessageChain a = MessageChain().Plain("你好!").Face(14);
MessageChain b = MessageChain().Plain("早安!").Face(14);
if(a==b) // true
```
这里a与b相等吗？（笔误？）
## 2
```
MessageChain().Plain("") == MessageChain().Plain("")
```
结果为false（Bug？）
在[MessageChain==实现部分的line88](https://github.com/cyanray/mirai-cpp/blob/6ba6cf03886c6acb399150d892772c4600833c3e/src/MessageChain.cpp#L88)
```
if (messages_[i] != mc.messages_[i]) return false;
```
是两个指针在作比较，改成
```
if (*messages_[i] != *mc.messages_[i]) return false;
```
解决了该问题

**Comment by cyanray** [comment]
卧槽，你发现了个大大大BUG！我的锅😓
