### ISSUE TITLE
在使用httplib::Client时出现错误

### ISSUE THREAD

**Issue by Longtianmu** [cyanray/mirai-cpp#143]
在使用httplib::Client进行POST时提示error C2079: “cli”使用未定义的 class“httplib::Client”

**Comment by Longtianmu** [comment]
换用其它HTTPLIB时会出现LNK2019: 无法解析的外部符号

**Comment by cyanray** [comment]
麻烦贴出详细代码，说明意图，方便我帮你分析问题。

**Comment by Longtianmu** [comment]
在main里仿照httplib官方示例使用如下代码进行POST的时候
`	httplib::Client cli("https://anime-api.5t5.top/v1/zth/console");
	httplib::Params params;
	params.emplace("name", "john");
	params.emplace("note", "coder");
	auto res = cli.Post("/post", params);`
会有如下报错
![image](https://user-images.githubusercontent.com/60567448/161203545-26a746d7-84e0-4845-b6fb-a89851c64609.png)

**Comment by cyanray** [comment]
> 在main里仿照httplib官方示例使用如下代码进行POST的时候 ![image](https://user-images.githubusercontent.com/60567448/161203639-41ca417c-7a76-4e6d-b69f-1d2e74c5286a.png) 会有如下报错 ![image](https://user-images.githubusercontent.com/60567448/161203545-26a746d7-84e0-4845-b6fb-a89851c64609.png)

尝试引用httplib的头文件：
```c++
#include <mirai/third-party/httplib.h>
```

mirai-cpp的较新版本采用了 pimpl idiom，会尽量避免在 MiraiBot.hpp 引入第三方库，尤其是 httplib。
因为引入 httplib 会同时引入 windows.h，会带来大量宏定义，导致莫名其妙的编译错误（比如SendMessage这个宏，和MiraiBot::SendMessage冲突了），这样不好。

**Comment by Longtianmu** [comment]
微软的这个宏定义属实是写了要挨打的那种（

**Comment by Longtianmu** [comment]
问题已解决 谢谢
