### ISSUE TITLE
有时QQ客户端收不到消息

### ISSUE THREAD

**Issue by 383494** [cyanray/mirai-cpp#145]
如题，有时在控制台显示发送了回复 但QQ客户端没有接收到 然后不知道怎么的又好了 过一会又不行了

**Comment by Numendacil** [comment]
mirai那边控制台显示发送成功的话应该就是被风控了，可以试试删除mirai/bots/{QQ号}/cache里的文件重新登录或者换一个device.json（不过就需要重新验证登录了）。前几天好像是查的比较严，可以时不时真人上号刷刷空间动态什么的挂一会。

**Comment by 383494** [comment]
谢谢 本来在论坛上查到打算删了这个issue的
但还是留下来给下面的萌新看吧
https://mirai.mamoe.net/topic/71/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-q-a
