### ISSUE TITLE
有关VoiceMessage的问题

### ISSUE THREAD

**Issue by Numendacil** [cyanray/mirai-cpp#146]
虽然 commit https://github.com/cyanray/mirai-cpp/commit/c8f668dc0f736f0470c2a425217eeaaafcb20f18 修复了相关的代码，但是貌似这个commit https://github.com/cyanray/mirai-cpp/commit/625b96a20b7591314d0e8ec625cef159e9bdf2a2 又把有问题的部分加回来了

在VoiceMessage.hpp的ToJson()函数中
`json result = 
{
				{ "type", type_ },
				{ "voiceId", voiceId_.empty() ? nullptr : voiceId_ },
				{ "url", url_.empty() ? nullptr : url_ },
				{ "path", path_.empty() ? nullptr : path_ },
				{ "base64", base64_.empty() ? nullptr : base64_ },
				{ "length", length_ }
			};
`
应改为
`
json result = 
			{
				{ "type", type_ },
				{ "length", length_ }
			};
`

**Comment by cyanray** [comment]
完了，怎么会这样呢……

**Comment by Numendacil** [comment]
#155
