### ISSUE TITLE
关于MessageChain().Add<VoiceMessage>();

### ISSUE THREAD

**Issue by misaka-20002** [cyanray/mirai-cpp#154]
`MessageChain mc;
        VoiceMessage vc;
string url = "http://music.163.com/song/media/outer/url?id=" + commands[1] + ".mp3";
        vc.Url(url);
        cout << vc.ToJson() << endl;
        mc.Add<VoiceMessage>(vc);
        cout << mc.ToJson() << endl;`

输出两行
{"base64":null,"length":12685285295766200576,"path":null,"type":"Voice","url":"http://music.163.com/song/media/outer/url?id=478654417.mp3","voiceId":null}

[{"base64":null,"length":12685285295766200576,"path":null,"type":"Voice","url":null,"voiceId":null}]
url参数神秘消失了

**Comment by Numendacil** [comment]
VoiceMessage的copy constructor写错了，我去提个PR

**Comment by cyanray** [comment]
试试 #155 有没有效果？

**Comment by misaka-20002** [comment]
git submodule update似乎没有什么用
我自己手动在本地同步更改了
现在在测试

**Comment by misaka-20002** [comment]
似乎还是不行

**Comment by misaka-20002** [comment]
![image](https://user-images.githubusercontent.com/91882141/198877651-b74d9886-8280-4d9d-9392-fe2bae9403ae.png)
现在copy constructor是这样
还是无效参数

**Comment by misaka-20002** [comment]
result那里也改了

**Comment by misaka-20002** [comment]
可能要明天才能给了（）
调试机关了

**Comment by misaka-20002** [comment]
好了解决了（）
确实是复制构造函数和length_没有赋初始0的问题
