### ISSUE TITLE
无法上传文件

### ISSUE THREAD

**Issue by naisuan** [cyanray/mirai-cpp#156]
报错信息：
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal

**Comment by cyanray** [comment]
你的代码贴一下，光靠错误信息看不出什么。

**Comment by naisuan** [comment]
抱歉
直接在 main() 中
`

	while (true)
	{
		try
		{
			cout << "尝试与 mirai-api-http 建立连接..." << endl;
			bot.Connect(opts);
			break;
		}
		catch (const std::exception &ex)
		{
			cout << ex.what() << endl;
		}
		MiraiBot::SleepSeconds(1);
	}
	cout << "Bot Working..." << endl;
	try
	{
		bot.UploadFileAndSend(群号_gid, "E:/code/mirai-cpp-template/src/main.cpp");
	}
	catch (const std::exception &ex)
	{
		cout << ex.what() << endl;
	}}
`

**Comment by Numendacil** [comment]
群文件上传路径错误 [MiraiBot.cpp](https://github.com/cyanray/mirai-cpp/blob/6a6d0b94064024f2e498bdb618601f34e95f3e47/src/MiraiBot.cpp#L533)，正确的路径为 `[POST] /file/upload` [Http Adapter](https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/HttpAdapter.md#%E7%BE%A4%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0)
