### ISSUE TITLE
SessionOptions 中，HttpPort 与 WebSocketPort 使用了错误的数据类型

### ISSUE THREAD

**Issue by samuv1119** [cyanray/mirai-cpp#159]
因为我需要使用签名系统,我将mirai-cpp-template中main函数开头设置SessionOption处的端口号进行了修改(改为36555)
并且把mirai-api-http的配置文件也进行了相应修改
但是mirai-cpp程序一直无法成功连接
我尝试了修改key为纯数字,关闭key验证,从本地对接服务器端mirai,锁定mirai-api-http版本为2.5.0,但是都没有起作用
然后我将签名系统的端口配置到8081,将mirai-cpp-template和mirai-api-http都配置到8080,连接成功
因此提出该issue
mirai-cpp-template项目使用WSL-GCC-Release编译,没有修改过mirai-cpp部分,和mirai-console-loader一起在ubantu22.04 64位服务器上运行,使用的mirai-api-http版本为2.5.0
因为本人技术不行,暂时只能提供这些信息

**Comment by ChihHao-Su** [comment]
我也遇到了相同的問題。我 debug 了一下，發現原因是 `SessionOptions` 的 `HttpPort` 和 `WebSocketPort` 用的是 short（眞聰明）。是故一旦端口號大於 32767，就歇菜了。

![图片](https://github.com/user-attachments/assets/4547c335-d2a7-4f66-adf0-99d12c405863)
![图片](https://github.com/user-attachments/assets/bd579c24-f669-446d-81be-562db9a3db55)

臨時的解決方法就是自己改一下 `mirai-cpp/include/mirai/SessionOptions.hpp`。

**Comment by ChihHao-Su** [comment]
我覺得應該改一下 issue 標題。

**Comment by cyanray** [comment]
😭写这玩意的时候可能头脑不清醒，丢人了。这个项目基本是 Archive 的状态，我不再有精力去维护了。感谢 @ChihHao-Su 。
