### ISSUE TITLE
图片消息如何使用代理发出

### ISSUE THREAD

**Issue by Jrsgslb** [cyanray/mirai-cpp#47]
如题

**Comment by cyanray** [comment]
如果是mirai-cpp与mirai-api-http的通信过程需要代理，可以尝试这样写(我没试过，如果有错误请回复，我再去尝试)：
```c++
// bot 是 MiraiBot 对象
bot.GetHttpClient()->set_proxy("host", port);
```

传输图片二进制数据到tx服务器的过程，由mirai实现。mirai-cpp作为一个mirai-api-http的sdk无法为这个过程设置代理。
