### ISSUE TITLE
不支持接收引用消息

### ISSUE THREAD

**Issue by zmdyy0318** [cyanray/mirai-cpp#56]
inline MiraiEvent MiraiEventStr(const std::string& miraiEvent)
函数中，不支持type=Quote的引用消息，导致会输出在控制台
消息接收json:
{"groupId":XXXXXXXXX,"id":XXXX,"origin":[{"id":XXXX,"time":1609736372,"type":"Source"},{"text":"[动画表情]","type":"Plain"}],"senderId":XXXX,"targetId":XXXXXXXXX,"type":"Quote"}

**Comment by cyanray** [comment]
是支持Quote消息的
这个和MiraiEventStr函数没关系（刚刚翻了翻代码才想起来）
会在控制台输出是因为 [include/mirai/defs/messages/QuoteMessage.hpp](https://github.com/cyanray/mirai-cpp/blob/master/include/mirai/defs/messages/QuoteMessage.hpp) 这个文件的`Set`函数有一句
```c++
std::cout << json.dump() << std::endl;
```
当初调试的时候忘记删除了。
