### ISSUE TITLE
使 mirai-cpp 的版本号与 mirai-api-http 的版本号相同

### ISSUE THREAD

**Issue by cyanray** [cyanray/mirai-cpp#60]
这样设计，就可以根据mirai-api-http的版本号选择mirai-cpp，保证兼容性。

**Comment by cyanray** [comment]
MiraiBot类提供了两个相关的函数：
1. GetMiraiCppVersion
2. GetMiraiApiHttpVersion

可以用这两个函数来获取 mirai-cpp 的版本号和 mirai-api-http 的版本号。如果两个版本号对不上，则可能存在兼容性问题（如果mirai-api-http有不兼容更新）。

**Comment by cyanray** [comment]
master 分支对应 mirai-api-http 的最新版。

**Comment by crested-ezios** [comment]
好像在mirai-api-http的版本为1.11时这个设计不起作用？

**Comment by cyanray** [comment]
> 

emmm 有的版本被跳过了，你可以用相近的版本（高版本一般兼容低版本，当然新功能用不了）
