### ISSUE TITLE
linux小白求助

### ISSUE THREAD

**Issue by Winter-is-comingXK** [cyanray/mirai-cpp#77]
我应该怎么登录qq号呢

**Comment by cyanray** [comment]
mirai-cpp 无法登录。
> mirai 是全开源 QQ 机器人 / QQ 协议支持库。(使用Kotlin编写)
> mirai-api-http 提供一系列 HTTP API 以便其他语言使用 mirai。
> 本项目为 mirai-api-http 的 C++ 封装，方便使用 C++ 开发基于 mirai-api-http 的插件。
> **在使用 mirai-cpp 和基于 mirai-cpp 的插件之前，你需要配置好 mirai-console 并且安装 mirai-api-http 插件。**

请先去了解 mirai。
