### ISSUE TITLE
请问能给一个json/xml发送的example吗

### ISSUE THREAD

**Issue by Winter-is-comingXK** [cyanray/mirai-cpp#81]
如题，我成功发送了一个json，但是客户端没有显示

**Comment by cyanray** [comment]
参考：

https://github.com/cyanray/mirai-cpp/blob/master/examples/RichMessage.cpp

json 格式的消息有可能是 **Json 类型消息**也有可能是 **App 类型消息**，类型不正确会不显示。

此外内容不正确（时效性参数过期）也可能导致不显示。
